### ISSUE TITLE
{{1}} shows up instead of Player Name

### ISSUE THREAD

**Issue by RiderExMachina** [breadbored/shortFlut#1]
Seen with the rule "{{0}}, tell us the zodiac sign of {{1}}, or {{1}} chooses how many sips you take!", the output is "Derp, tell us the zodiac sign of Derpina, or {{1}} chooses how many sips you take!".

This seems to be because JS's `replace()` function only replaces the first instance it finds. This should be fixed by changing [Line 65 in play.js](https://github.com/breadbored/shortFlut/blob/master/play.js#L65) to `ruleText = ruleText.replace(/{{ + i.toString() + }}/g, possPlayers[t]);` or something similar.

**Comment by breadbored** [comment]
Thanks for the feedback. I wasn't sure if JS was going to replace all of them and that was a rule I reworded only a few hours ago.

I'll apply your change and report back

**Comment by RiderExMachina** [comment]
Disclaimer that JS is not my native language, so it may take more finagling. [Here's the first thing I found](https://stackoverflow.com/questions/1144783/how-to-replace-all-occurrences-of-a-string) when I Googled it. The second answer seems the most promising.

**Comment by breadbored** [comment]
I attempted to fix in 3fb6dcc8790d5d4a35dfe32cb24e538f890c4d53 however I decided to commit without testing (dumb).

I attempted to commit multiple times before I got to a computer to test and fix it (dumb dumb dumb).

It is now fixed in 7cea3300ab8d5951d8908391af67a606f5e247f4

Thanks for finding that!

**Comment by breadbored** [comment]
I also don't work in JS, but I should have known better for the later issues since doing REGEX is my job.
